@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.molsoncad.masterangler.loot;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;