@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.molsoncad.masterangler.mixin;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;