@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.molsoncad.masterangler.loot.conditions;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;