@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.molsoncad.masterangler.entity;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;